### ISSUE TITLE
Patch deletes Teamspeak bin

### ISSUE THREAD

**Issue by JonesGreen** [FelixVolo/TS5AddonInstaller#2]
Hi,
I just tried your installer. Sadly I'm hitting some kind of bug. When the program tries to patch Teamspeak the binary file is gone after it says that it was successful.

Same with running java -jar TS5AddonInstaller-2.5.0-all.jar -patch /home/test/TS5/ from cli

I'm on TS5 b77 and Archlinux with Openjdk 17.0.9

**Comment by Exopandora** [comment]
Thanks for the report! Have you installed teamspeak in a protected directory? If so, please make sure the installer is launched with `sudo`. Techincally, the installer never deletes a file. Instead, the original file is just renamed to `<name>.bak` and the patched file (copy of original file) is moved/renamed from the temp directory to the teamspeak directory. The file will only be moved when it passes hash validation.

**Comment by JonesGreen** [comment]
Hi thanks for your reply. I checked again I have TS5 sitting in my home directory permissions should be fine (TS5 self update also works). But when I run

java -jar TS5AddonInstaller-2.5.0-all.jar -patch /home/test/TS5/

I have a TeamSpeak.bak file being created but the patched file is not in the root directory of TS5 after it is finished. Not sure what the issue could be :/

Edit:

Hi just checked my /tmp folder and there are a bunch of files with random numbers. I got the md5sum of e.g. file 17151032061822015559 and it matches the "patched": "0bc778091a1e74f8eda9b56180cfb390" from patches.json. So it seems that the patched file from /tmp for some reasons is not being moved/copied back to the TS5 folder.

So I manually copied the file over and renamed it to TeamSpeak. Then I installed BetterChat again. And it works.

Edit2:

did some digging it seems on my end in file:

Patcher.java, line 83, patched.renameTo(file);

always returns false, but no idea why.

**Comment by Exopandora** [comment]
Thanks for the futher analysis. You could try changing lines 82-83 in Patcher.java to:
```java
Files.move(file.toPath(), backup.toPath());
Files.move(patched.toPath(), file.toPath());
```
or even
```java
Files.move(file.toPath(), backup.toPath(), java.nio.file.StandardCopyOption.ATOMIC_MOVE);
Files.move(patched.toPath(), file.toPath(), java.nio.file.StandardCopyOption.ATOMIC_MOVE);
```

**Comment by JonesGreen** [comment]
hi, I tried 

`Files.move(file.toPath(), backup.toPath());
Files.move(patched.toPath(), file.toPath());`

and it worked fine!

**Comment by Exopandora** [comment]
Thanks again for reporting! This should be fixed for new releases.
